"""Render findings into something a busy person reads on a phone.

Two bodies are produced from one set of findings: plain text (Slack, and the
text/plain part of the email, which is also what lands in data/alerts/) and
HTML. They carry the same information — the HTML never has a fact the text
lacks, so a plain-text reader is never worse informed.
"""

from __future__ import annotations

import html
from dataclasses import dataclass

from .channels import Alert
from .rules import Finding, overall_severity

_BADGE = {"info": "#2563eb", "warning": "#b45309", "critical": "#b91c1c"}


@dataclass
class Context:
    """Headline numbers shown above the findings, for orientation."""

    month: str = ""
    actual: float | None = None
    budget: float | None = None
    variance: float | None = None
    headcount: float | None = None


def _headline(ctx: Context) -> list[str]:
    if not ctx.month:
        return []
    lines = [f"Period: {ctx.month}"]
    if ctx.actual is not None and ctx.budget is not None:
        pct = (ctx.actual - ctx.budget) / ctx.budget if ctx.budget else 0.0
        lines.append(f"Actual ${ctx.actual:,.0f} vs budget ${ctx.budget:,.0f} "
                     f"({pct:+.1%})")
    if ctx.headcount is not None:
        lines.append(f"Headcount {ctx.headcount:,.0f} FTE")
    return lines


def render_text(findings: list[Finding], ctx: Context | None = None) -> str:
    ctx = ctx or Context()
    parts: list[str] = []
    parts.extend(_headline(ctx))
    if parts:
        parts.append("")

    if not findings:
        parts.append("No thresholds breached. Nothing needs attention.")
        return "\n".join(parts)

    parts.append(f"{len(findings)} finding(s):")
    for i, f in enumerate(findings, 1):
        parts.append("")
        parts.append(f"{i}. [{f.severity.upper()}] {f.title}")
        parts.append(f"   {f.detail}")
    return "\n".join(parts)


def render_html(findings: list[Finding], ctx: Context | None = None) -> str:
    ctx = ctx or Context()
    head = "".join(f"<p style='margin:2px 0;color:#334155'>{html.escape(line)}</p>"
                   for line in _headline(ctx))

    if findings:
        rows = []
        for f in findings:
            colour = _BADGE[f.severity]
            rows.append(
                f"<tr><td style='padding:12px 0;border-top:1px solid #e2e8f0'>"
                f"<span style='display:inline-block;padding:2px 8px;border-radius:9999px;"
                f"background:{colour};color:#fff;font-size:11px;font-weight:700;"
                f"letter-spacing:.04em'>{f.severity.upper()}</span>"
                f"<div style='font-weight:600;margin:6px 0 2px;color:#0f172a'>"
                f"{html.escape(f.title)}</div>"
                f"<div style='color:#475569;font-size:14px;line-height:1.5'>"
                f"{html.escape(f.detail)}</div></td></tr>")
        body = f"<table style='width:100%;border-collapse:collapse'>{''.join(rows)}</table>"
    else:
        body = ("<p style='color:#15803d;font-weight:600'>No thresholds breached. "
                "Nothing needs attention.</p>")

    return (
        "<div style=\"font-family:-apple-system,Segoe UI,Roboto,sans-serif;"
        "max-width:640px;margin:0 auto;padding:24px;color:#0f172a\">"
        "<h1 style='font-size:18px;margin:0 0 4px'>Helios alert digest</h1>"
        f"{head}<div style='height:12px'></div>{body}"
        "<p style='margin-top:24px;color:#94a3b8;font-size:12px'>"
        "Generated by Helios. Data is synthetic.</p></div>")


def build(findings: list[Finding], ctx: Context | None = None,
          subject: str | None = None) -> Alert:
    """Package findings into a deliverable Alert.

    The subject line leads with the count and worst severity because that is all
    a phone notification shows.
    """
    level = overall_severity(findings)
    ctx = ctx or Context()
    if subject is None:
        if findings:
            subject = f"Helios: {len(findings)} finding(s) [{level.upper()}]"
        else:
            subject = "Helios: all clear"
        if ctx.month:
            subject += f" - {ctx.month}"
    return Alert(
        subject=subject,
        body_text=render_text(findings, ctx),
        body_html=render_html(findings, ctx),
        level=level,
        metadata={"n_findings": len(findings),
                  "codes": [f.code for f in findings],
                  "month": ctx.month},
    )
